author: KingFisher
commands:
    purgemonitor:
        description: Allows to purge the database, be careful with this command, it deletes all the data collected by ServerMonitor.
        permission: servermonitor.purgemonitor
        usage: /purgemonitor
description: Allows to collect data about the server, and to view the data as charts.
load: STARTUP
main: com.kingfisher.servermonitor.ServerMonitor
name: ServerMonitor
permissions:
    servermonitor.*:
        children:
            servermonitor.purgemonitor: true
        default: op
        description: Allows to run all ServerMonitor commands.
    servermonitor.purgemonitor:
        default: op
        description: Allows to run the /purgemonitor command.
version: 0.0.1
website: 'Source code: https://github.com/King-Fisher/ServerMonitor ||| CI: http://ci.nixium.com/job/ServerMonitor/'